default: &default
  adapter: mysql2
  database: webs
  host: localhost
  username: root
  password:
  pool: 5
  timeout: 5000
  encoding: utf8

development:
  <<: *default
  database: dev_awesomes

test:
  <<: *default
  database: test_awesomes

production:
  <<: *default
  database: <%= ENV['MYSQL_DATABASE'] %>
  host: <%= ENV['MYSQL_HOST'] %>
  username: <%= ENV['MYSQL_USERNAME'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>

